name: PR-to-master
on:
    pull_request:
        branches:
            - master
jobs:
    cache-and-install:
        runs-on: ubuntu-latest
        timeout-minutes: 2

        steps:
            - name: Checkout repository code
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.18.0

            - uses: pnpm/action-setup@v2
              name: Install pnpm
              with:
                  version: 8
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - uses: actions/cache@v3
              name: Setup pnpm cache
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install

            - name: Check formatting
              run: pnpm prettier-check
